name: ci
'on':
  push:
    branches:
      - master
  pull_request: {}
env:
  DOCS_APP_ARTIFACT_NAME: demo
  DOCS_APP_PATH: dist/apps/demo/
  NODE_OPTIONS: '--max-old-space-size=6144'
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.head_ref }}'
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Validate
        run: npx prettier --check .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
  unit:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Build
        run: npx nx build demo --base-href=/ngx-breakpoint-observer/
      - name: Upload demo website
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: '${{ env.DOCS_APP_ARTIFACT_NAME }}'
          path: '${{ env.DOCS_APP_PATH }}'
          retention-days: 1
  deploy-demo:
    name: '[Merge] Deploy demo website'
    needs:
      - build
      - unit
      - build-demo
    if: github.event_name == 'push' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: '${{ steps.deploy.outputs.page_url }}'
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: |-
        ${{ github.workflow }}-deploy-demo-${{
          github.event_name == 'push'
            && github.ref
            || github.head_ref
        }}
      cancel-in-progress: "${{ github.event_name != 'push' }}"
    steps:
      - name: Download demo website
        uses: actions/download-artifact@v3
        with:
          name: '${{ env.DOCS_APP_ARTIFACT_NAME }}'
          path: '${{ env.DOCS_APP_PATH }}'
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v1
      - name: Upload GitHub Pages-compatible tarball
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{ env.DOCS_APP_PATH }}'
      - name: Deploy demo website tarball
        id: deploy
        uses: actions/deploy-pages@v1
